
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.8.3+195e7f5a3 для .NET Framework
      Сборка начата 20.09.2024 22:13:36.
      
      Проект "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Структурированный вывод включен. Форматирование диагностики компилятора будет отражать иерархию ошибок. Подробнее см. https://aka.ms/cpp/structured-output.
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.74
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/3.28.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.8.3+195e7f5a3 для .NET Framework
      Сборка начата 20.09.2024 22:13:37.
      
      Проект "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Структурированный вывод включен. Форматирование диагностики компилятора будет отражать иерархию ошибок. Подробнее см. https://aka.ms/cpp/structured-output.
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.70
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-7s2oks"
      binary: "C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-7s2oks"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-7s2oks'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_4ac2d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.8.3+195e7f5a3 для .NET Framework
        Сборка начата 20.09.2024 22:13:38.
        
        Проект "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-7s2oks\\cmTC_4ac2d.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_4ac2d.dir\\Debug\\".
          Структурированный вывод включен. Форматирование диагностики компилятора будет отражать иерархию ошибок. Подробнее см. https://aka.ms/cpp/structured-output.
          Создание каталога "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-7s2oks\\Debug\\".
          Создание каталога "cmTC_4ac2d.dir\\Debug\\cmTC_4ac2d.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_4ac2d.dir\\Debug\\cmTC_4ac2d.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_4ac2d.dir\\Debug\\cmTC_4ac2d.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_4ac2d.dir\\Debug\\\\" /Fd"cmTC_4ac2d.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.38.33130 для x64
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_4ac2d.dir\\Debug\\\\" /Fd"cmTC_4ac2d.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-7s2oks\\Debug\\cmTC_4ac2d.exe" /INCREMENTAL /ILK:"cmTC_4ac2d.dir\\Debug\\cmTC_4ac2d.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-7s2oks/Debug/cmTC_4ac2d.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-7s2oks/Debug/cmTC_4ac2d.lib" /MACHINE:X64  /machine:x64 cmTC_4ac2d.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_4ac2d.vcxproj -> C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-7s2oks\\Debug\\cmTC_4ac2d.exe
        FinalizeBuildStatus:
          Файл "cmTC_4ac2d.dir\\Debug\\cmTC_4ac2d.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_4ac2d.dir\\Debug\\cmTC_4ac2d.tlog\\cmTC_4ac2d.lastbuildstate".
        Сборка проекта "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-7s2oks\\cmTC_4ac2d.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.74
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-i1sfds"
      binary: "C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-i1sfds"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-i1sfds'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_f8cd8.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.8.3+195e7f5a3 для .NET Framework
        Сборка начата 20.09.2024 22:13:39.
        
        Проект "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-i1sfds\\cmTC_f8cd8.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_f8cd8.dir\\Debug\\".
          Структурированный вывод включен. Форматирование диагностики компилятора будет отражать иерархию ошибок. Подробнее см. https://aka.ms/cpp/structured-output.
          Создание каталога "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-i1sfds\\Debug\\".
          Создание каталога "cmTC_f8cd8.dir\\Debug\\cmTC_f8cd8.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_f8cd8.dir\\Debug\\cmTC_f8cd8.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_f8cd8.dir\\Debug\\cmTC_f8cd8.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f8cd8.dir\\Debug\\\\" /Fd"cmTC_f8cd8.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.38.33130 для x64
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f8cd8.dir\\Debug\\\\" /Fd"cmTC_f8cd8.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-i1sfds\\Debug\\cmTC_f8cd8.exe" /INCREMENTAL /ILK:"cmTC_f8cd8.dir\\Debug\\cmTC_f8cd8.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-i1sfds/Debug/cmTC_f8cd8.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/GitHub_Repos/mp2-lab1-set/sln/vc22/CMakeFiles/CMakeScratch/TryCompile-i1sfds/Debug/cmTC_f8cd8.lib" /MACHINE:X64  /machine:x64 cmTC_f8cd8.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_f8cd8.vcxproj -> C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-i1sfds\\Debug\\cmTC_f8cd8.exe
        FinalizeBuildStatus:
          Файл "cmTC_f8cd8.dir\\Debug\\cmTC_f8cd8.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_f8cd8.dir\\Debug\\cmTC_f8cd8.tlog\\cmTC_f8cd8.lastbuildstate".
        Сборка проекта "C:\\GitHub_Repos\\mp2-lab1-set\\sln\\vc22\\CMakeFiles\\CMakeScratch\\TryCompile-i1sfds\\cmTC_f8cd8.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.67
        
      exitCode: 0
...
